import fs from 'node:fs';
import path from 'node:path';

/**
 * The on-demand routes: only mounted when the Cloudflare adapter is on, since
 * they need a runtime to run in (see astro.config.mjs).
 *
 * 1. Every page under `src/pages/[lang]/` a second time, at
 *    `/preview/[lang]/…`. The site is static: the published pages are HTML
 *    files made once per build. A preview has to show a draft that has never
 *    been published, so it cannot be a file - it has to be rendered when
 *    asked for. Rather than maintain a second set of page components for
 *    that, this reuses the same files: the same route pattern, the same
 *    `Astro.params`, the same frontmatter. The only thing that changes is the
 *    client the queries run through, which src/middleware.ts swaps for a
 *    drafts-reading one on every `/preview/` request.
 *
 *    Each preview route is a generated two-line wrapper in `src/preview/`
 *    (gitignored) that opts out of prerendering and renders the real page.
 *    Injecting the page file itself with `prerender: false` does not work:
 *    prerendering is decided per component, so the original route would go
 *    on-demand with it and the site would stop being static.
 *
 * 2. The admin API and the preview door under `/api/`, from
 *    `src/server/routes/`. They live outside `src/pages/` on purpose: a page
 *    file that opts out of prerendering makes the plain static build refuse
 *    to run without an adapter.
 */
export function previewRoutes({ prefix = '/preview', pagesDir = 'src/pages/[lang]', outDir = 'src/preview' } = {}) {
  return {
    name: 'ceramic-brussels:preview-routes',
    hooks: {
      'astro:config:setup': ({ injectRoute, config, logger }) => {
        const rootPath = fsPath(new URL(pagesDir.replace(/\/?$/, '/'), config.root));
        const outPath = fsPath(new URL(outDir.replace(/\/?$/, '/'), config.root));

        fs.rmSync(outPath, { recursive: true, force: true });

        const files = walk(rootPath).filter((f) => f.endsWith('.astro'));
        for (const file of files) {
          const rel = path.relative(rootPath, file).split(path.sep).join('/');
          const pattern = `${prefix}/[lang]/${rel.replace(/\.astro$/, '').replace(/(^|\/)index$/, '')}`.replace(/\/$/, '');

          const wrapper = path.join(outPath, rel);
          const target = path.relative(path.dirname(wrapper), file).split(path.sep).join('/');
          fs.mkdirSync(path.dirname(wrapper), { recursive: true });
          fs.writeFileSync(
            wrapper,
            `---
// Generated by src/integrations/preview-routes.mjs - do not edit, not committed.
export const prerender = false;
import Page from '${target.startsWith('.') ? target : `./${target}`}';
---

<Page />
`,
          );

          injectRoute({
            pattern,
            entrypoint: `./${path.posix.join(outDir, rel)}`,
            prerender: false,
          });
        }

        injectRoute({ pattern: '/api/preview/enable', entrypoint: './src/server/routes/preview-enable.ts', prerender: false });
        injectRoute({ pattern: '/api/preview/disable', entrypoint: './src/server/routes/preview-disable.ts', prerender: false });
        injectRoute({ pattern: '/api/[...path]', entrypoint: './src/server/routes/api.ts', prerender: false });

        logger.info(`${files.length} preview routes mounted under ${prefix}/, plus /api/`);
      },
    },
  };
}

function fsPath(url) {
  return decodeURIComponent(url.pathname).replace(/^\/([A-Za-z]:)/, '$1');
}

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}
